### ISSUE TITLE
using gradle kotlin dsl

### ISSUE THREAD

**Issue by richardmio** [spring-guides/top-spring-boot-docker#2]
It seems gradle kotlin dsl grammar is quite different from the gradle in this tutorial. Are we able to have one tutorial for gradle kotlin dsl as well?

**Comment by dsyer** [comment]
Thanks for the suggestion. I think anyone who is able to use the kotlin dsl will be able to work it out for themselves, though. It's not really possible to cover all the possible build tools in a guide that isn't related to build tools.
